language:
  node_js
node_js:
  - "10"
before_script:
  - yarn
script:
  - yarn test --coverage --watchAll=false
after_success:
  - test $TRAVIS_BRANCH = "master" && npx codecov --token=$CODECOV_TOKEN
